// --- START OF FILE tutorial.js ---

const tutorialBox=document.getElementById('tutorial-box'),tutorialTitle=document.getElementById('tutorial-title'),tutorialContent=document.getElementById('tutorial-content'),nextBtn=document.getElementById('tutorial-next-btn');
const tutorialSteps=[{title:"Welcome!",content:"Welcome to Drake Merger RPG! Merge drakes for powerful evolutions."},{title:"Buying Drakes",content:"Click 'Buy Drake Egg' to start. Costs Resources."},{title:"Resources",content:"Drakes generate Resources. Higher levels & Focus = more!"},{title:"Merging",content:"Drag a drake onto another of *same level*. They merge & inherit traits."},{title:"Grid Space",content:"Space is limited! Merging frees slots."},{title:"Rarity",content:"Drakes have Rarity (Common-Epic)! See border color. Rarer = better stats/potential. Merge for chance of rarer!"},{title:"Elements",content:"Each drake has Element (🔥,💧,🌍...). Affects income/combat!"},{title:"Stats",content:"Drakes have stats!\n • Focus boosts income.\n • Strength boosts damage.\n • Vitality increases HP.\n • Agility boosts crit/dodge. Click drake for details!"},{title:"Potential",content:"Determines stat improvement on merge. Higher = better growth!"},{title:"Drake Details",content:"Click drake to see Level, Rarity, Element, Stats, Potential, income."},{title:"Combat Arena",content:"Drag drakes to 'Combat Arena' team slots. Click 'Start Combat' to fight waves for Essence & Shards!"},{title:"Saving",content:"Use 'Save Game' often! Old saves might not work."},{title:"That's It!",content:"Merge, fight, discover rare drakes! Good luck!"}];
let currentStep=0,tutorialActive=false;
export function initTutorial(){if(nextBtn)nextBtn.addEventListener('click',nextTutorialStep);else console.warn("Tutorial Next Btn missing.");}
export function startTutorial(){console.log("Starting tutorial...");currentStep=0;tutorialActive=true;if(tutorialBox){showStep(currentStep);tutorialBox.classList.remove('hidden');}else{console.error("Tutorial box missing.");}}
function nextTutorialStep(){currentStep++;if(currentStep<tutorialSteps.length){showStep(currentStep);}else{closeTutorial();}}
function showStep(stepIndex){if(!tutorialTitle||!tutorialContent||!nextBtn)return;if(stepIndex<0||stepIndex>=tutorialSteps.length)return;const step=tutorialSteps[stepIndex];tutorialTitle.textContent=step.title;tutorialContent.innerHTML=step.content.replace(/\n/g,'<br>');nextBtn.textContent=(stepIndex===tutorialSteps.length-1)?"Finish":"Next";}
export function closeTutorial(){tutorialActive=false;if(tutorialBox)tutorialBox.classList.add('hidden');}
export function isTutorialActive(){return tutorialActive;}

// --- END OF FILE tutorial.js ---